<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="NAlumnosGestionAnterior";
$icono="icon-user";
$subtitulo1="DatosAlumnos";
$jsFile="alumno/reinscripcion.js";
include_once("../../listar/tmplistado.php");
?>