<?php
include_once("../../login/check.php");
$titulo="NDatosAlumnos";
$icono="icon-cog";
$subtitulo1="DatosAlumnos";
$folder="../../";
$jsFile="alumno/datosalumnos.js";
include_once("../../listar/listado.php");
?>