<?php
include_once("../../login/check.php");
$folder="../../";
$jsFile="docente/modificarcasilleros.js";
$titulo="NModificarCasilleros";
$subtitulo1="Listado";
$subtitulo2="Configuracion";
$direccion="-";
$archivoInicial="formulario.php";
include_once("../../listar/docente.php");
?>