<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="NResultadosEvaluacionDocente";
$subtitulo1="Configuracion";
$subtitulo2="Reporte";
$direccion="-";
$archivoInicial="formulario.php";
$jsFile="docente/resultadosevaluacion.js";
include_once("../../listar/docente.php");
?>