<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="NAsignacionMateriasDocente";
$subtitulo1="Configuracion";
$subtitulo2="Listado";
$jsFile="docente/materia.js";
$archivoInicial="formulario.php";
include_once("../../listar/docente.php");
?>