<?php
session_start();
include_once("../../login/check.php");
$titulo="NInscribirHermano";
$icono="icon-cog";
$subtitulo1="Configuracion";
$folder="../../";
$jsFile="alumno/inscribirhermano.js";
include_once("../../listar/listado.php");
?>