<?php
$idioma=array();
//Login
$idioma['Usuario']="Usuario";

$idioma['Ingresar']="Ingresar";
$idioma['Comunicados']="Comunicados";
$idioma['Idioma']="Idioma";
$idioma['NoPuedeIngresar']="¿No puedes acceder al Sistema?";
$idioma['Pie']="Sistema Académico Administrativo";
$idioma['NoComunicados']="NO HAY COMUNICADOS";
$idioma['NoDatos']="Por favor introdusca TODOS los DATOS.";
$idioma['DatosErroneos']="El USUARIO o la CONTRASEÑA son incorrectos, verifique e intente nuevamente.";
//Inicio
$idioma['TituloSistema']="Sistema Académico Administrativo para Colegios";
$idioma['Configuracion']="Configuración";
$idioma['Notificacion']="Notificaciones";
$idioma['TareaPendiente']="Tareas Pendientes";
$idioma['Mensajes']="Mensajes";
$idioma['Agenda']="Agenda";
$idioma['Salir']="Salir";

$idioma['ReporteImpresion']="Este Reporte Generado es para Imprimir";
//Menu
$idioma['Menu']="Menú";
$idioma['Inicio']="Inicio";

//Navegación
$idioma['NInscripcionAlumnoNuevo']="Inscripción Alumno Nuevo";
$idioma['NTarjetaCuotas']="Tarjeta de Cuotas";
$idioma['NRegistrarRude']="Registrar Rude";
$idioma['NModificarRude']="Modificar Rude";
$idioma['NImpresionRude']="Impresión de Rude";
$idioma['NPagarCuotas']="Pagar Cuotas";
$idioma['NVerDeudores']="Ver Deudores";
$idioma['NArqueoCaja']="Arqueo de Caja";
$idioma['NAlumnoPorCurso']="Alumno por Curso";
$idioma['NAlumnoPorCursoPersonalizado']="Alumno por Curso Personalizado";
$idioma['NReporteBecados']="Reporte Becados";
$idioma['NTodosLosBecados']="Todos los Becados";
$idioma['NFrecuenciaAccesos']="Frecuencia de Accesos";
$idioma['NModificarDatosDocente']="Modificar Datos Docente";
$idioma['NImpresionBoletin']="Impresión de Boletín";
//Generales
$idioma['Curso']="Curso";
$idioma['Alumnos']="Alumnos";
$idioma['Alumnas']="Alumnas";
$idioma['Estadísticas']="Estadísticas";
$idioma['TarjetaCuotas']="Tarjeta de Cuotas";
$idioma['BoletaDatos']="Boleta de Datos";
$idioma['PagarCuotas']="Pagar Cuotas";

$idioma['Configuracion']="Configuración";
$idioma['Guardar']="Guardar";

$idioma['Hombres']="Hombres";
$idioma['Mujeres']="Mujeres";
$idioma['AmbosSexos']="Ambos Sexos";
$idioma['Curso']="Curso";
$idioma['Nombre']="Nombre";
$idioma['Nombres']="Nombres";
$idioma['Apellido']="Apellido";
$idioma['Apellidos']="Apellidos";
$idioma['Apellido Paterno']="Apellido Paterno";
$idioma['Apellido Materno']="Apellido Materno";
$idioma['Colegio']="Colegio";
$idioma['Rude']="Rude";
$idioma['Paterno']="Paterno";
$idioma['Materno']="Materno";
$idioma['Contraseña']="Contraseña";
$idioma['CambiarContraseña']="Cambiar Contraseña";
$idioma['Sexo']="Sexo";
$idioma['FechaNacimiento']="Fecha de Nacimiento";
$idioma['Departamento']="Departamento";
$idioma['Provincia']="Provincia";
$idioma['Direccion']="Dirección";
$idioma['Celular']="Celular";
$idioma['EstadoCivil']="Estado Civil";
$idioma['Email']="Email";
$idioma['Dato']="Dato";
$idioma['Datos']="Datos";
$idioma['Foto']="Foto";
$idioma['Fotos']="Fotos";
$idioma['DatosPersonales']="Datos Personales";
$idioma['DatosTrabajo']="Datos de Trabajo";
$idioma['Cargo']="Cargo";
$idioma['Antiguedad']="Antiguedad";
$idioma['Categoria']="Categoria";
$idioma['CargaHoraria']="Carga Horaria";
$idioma['Observacion']="Observación";
$idioma['DatosFormacionProfesional']="Datos de Formación Profesional";
$idioma['Universidad']="Universidad";
$idioma['AñoIngreso']="Año de Ingreso";
$idioma['AñoEgreso']="Año de Egreso";
$idioma['AñoTitulacion']="Año de Titulación";
$idioma['Titulo']="Título";
$idioma['Telefono']="Teléfono";
$idioma['AbrirOtraVentana']="Abrir en Otra Ventana";
$idioma['Ninguno']="Ninguno";
$idioma['Por']="Por";
$idioma['Docente']='Docente';
$idioma['Dia']="Día";
$idioma['FechaAcceso']="Fecha Acceso";
$idioma['HoraAcceso']="Hora Acceso";
$idioma['Volver']="Volver";
$idioma['Regresar']="Regresar";
$idioma['Atras']="Atras";
$idioma['BuscarAlumnoPor']="Buscar alumno por...";
$idioma['BuscarCursoPor']="Buscar curso por...";
$idioma['BuscarDocentePor']="Buscar docente por...";
$idioma['Ingrese']="Ingrese";
$idioma['Femenino']="Femenino";
$idioma['Masculino']="Masculino";
$idioma['IngreseSu']="Ingrese su ";
$idioma['IngreseSus']="Ingrese sus ";
$idioma['DatosGuardadosCorrectamente']="Los datos se guardaron Correctamente";
$idioma['DatosGuardadosError']="Hubo un EROR al Guardar los datos, Revise los datos e Intente Nuevamente ";
$idioma['SeguroCambiarContraseña']="¿Está seguro que desea cambiar la contraseña?";
$idioma['NoseCambiaraPosteriormente']="No se Cambiará Posteriormente";
$idioma['NoseGuardo']="No se Guardo";
$idioma['Actualizar']="Actualizar";
$idioma['ActualizarPagina']="Actualizar Página";
$idioma['ActualizarVentana']="Actualizar Ventana";
$idioma['Seleccionar']="Seleccionar";
$idioma['ExportarExcel']="Exportar tabla a excel";
$idioma['Activo']="Activo";
$idioma['Desactivar']="Desactivar";
$idioma['ReporteGeneral']="Reporte General";
$idioma['ReporteGeneralImpresion']="Reporte para Impresión";
$idioma['Buscador']="Buscador";
$idioma['Gestion']="Gestión";
$idioma['Fecha']="Fecha";
$idioma['Fechas']="Fechas";
$idioma['Hora']="Hora";
$idioma['CantidadTotal']="Cantidad Total";
$idioma['Cursos']="Cursos";
$idioma['Eliminar']="Eliminar";
//Titulos de Página
$idioma['HojaCasilleros']="Hoja de Casilleros";
//Rude
$idioma['RegistrarRude']="Registrar Rude";
$idioma['ModificarRude']="Modificar Rude";
$idioma['RudeAlumno']="Rude del Alumno";
$idioma['TodoEnMayusculas']="Todos los datos en Mayusculas";
$idioma['RudeYaRegistrado']="YA SEA REGISTRADO EL RUDE DE ESTE ALUMNO";
$idioma['QuiereModificarlo']="SI QUIERE MODIFICARLO Click EN EL SIGUIENTE BOTON";
$idioma['DatosDelEstudiante']="Datos del Estudiante";
$idioma['DatosInscripcionActual']="Datos Inscripción Actual";
$idioma['DireccionActualEstudiante']="Dirección Actual del Estudiante";
$idioma['AspectosSociales']="Aspectos Sociales";
$idioma['DatosDelPadreTutor']="Datos del Padre o Tutor";
$idioma['DatosMadre']="Datos de la Madre";
$idioma['Documentos']="Documentos";
//Pdf
$idioma['Pagina']="Página";
$idioma['FechaActual']="Fecha Actual";
$idioma['Primera']="Primera";
$idioma['Segunda']="Segunda";
$idioma['Tercera']="Tercera";
$idioma['Cuarta']="Cuarta";
$idioma['Quinta']="Quinta";
$idioma['Sexta']="Sexta";
$idioma['Septima']="Septima";
$idioma['Octava']="Octava";
$idioma['Novena']="Novena";
$idioma['Decima']="Decima";
$idioma['Si']="Sí";
$idioma['Desde']="Desde";
$idioma['Hasta']="Hasta";
//Estadisticas
$idioma['NoHayAlumnoNuevo']="No Existen Alumnos Registrados para este Curso";
$idioma['VerAlumnosNuevos']="Ver Alumnos Nuevos";
$idioma['CantidadTotalInscritos']="Cantidad Total de Inscritos";
$idioma['Nuevos']="Nuevos";
$idioma['AlumnosNuevos']="Alumnos Nuevos";
$idioma['TodoColegio']="Todo el Colegio";
//Cuotas
$idioma['Factura']="Factura";
$idioma['Cuota']="Cuota";
$idioma['Total']="Total";
$idioma['Monto']="Monto";
$idioma['FechaPago']="Fecha de Pago";
$idioma['Archivo']="Archivo";
$idioma['MontoPagar']="Monto a Pagar";
$idioma['Descuento']="Descuento";
$idioma['Nit']="NIT";
$idioma['FacturarA']="Facturar A";
$idioma['APagar']="A Pagar";
$idioma['Estado']="Estado";
$idioma['Menor']="Menor";
$idioma['Observaciones']="Observaciones";
$idioma['Revisar']="Revisar";
$idioma['Igual']="Igual";
$idioma['ALa']="A la";
//Deudores
$idioma['ArqueoCaja']="Arqueo de Caja";
$idioma['AlumnosMora']="Alumnos con Mora";
$idioma['NombreCompleto']="Nombre Completo";
$idioma['LimiteCuota']="Limite de Cuota";
$idioma['Total']="Total";

//Reporte
$idioma['NominaAlumnos']="Nomina de Alumnos";
$idioma['FechaNac']="FechaNac";
$idioma['Ci']="CI";
$idioma['TelefonoCasa']="TelefonoCasa";
$idioma['CelularP']="CelularP";
$idioma['CelularM']="CelularM";
$idioma['Reporte']="Reporte";
$idioma['MontoBeca']="Monto de Beca";
$idioma['AlumnoBecado']="Alumno Becado";
$idioma['VerReporte']="Ver Reporte";
$idioma['TodoBecados']="Todos los Becados";
$idioma['Campo1']="Campo 1";
$idioma['Campo2']="Campo 2";
$idioma['DibujarBorde']="Dibujar Borde";
$idioma['DibujarSombra']="Dibujar Sombra";
$idioma['SoloCasillasBlanco']="Solo Casillas en Blanco";

//Docente
$idioma['FrecuenciaAcceso']="Frecuencia de Accesos";
$idioma['CantidadAcceso']="Cantidad de Accesos";
$idioma['UltimoAcceso']="Ultimo Acceso";
$idioma['DescargarHojaCasilleros']="Descargar Hoja de Casilleros";
$idioma['VerFechas']="Ver Fechas";
$idioma['VerDatosDocente']="Ver Datos del Docente";
$idioma['ModificarDatosDocente']="Modificar Datos del Docente";
$idioma['ReporteDatosDocente']="Reporte Datos del Docente";
$idioma['ReporteTodosDocente']="Reporte Datos del Docente";
$idioma['DatosDocente']="Datos del Docente";
$idioma['ReporteTodosDatosDocente']="Reporte Todos los Docentes";
$idioma['RegistroNuevoDocente']="Registro Nuevo Docente";
$idioma['AñoI']="Año Ing";
$idioma['AñoE']="Año Eg";
$idioma['AñoT']="Año Tit";

//Notas
$idioma['Boletin']="Boletín";
$idioma['RegistrarImpresion']="Registrar Impresión";
$idioma['MostrarImpresion']="Mostrar Impresión";
$idioma['EstadisticaAgenda']="Estadistica de la Agenda";
$idioma['Faltas']="Faltas";
$idioma['Atrasos']="Atrasos";
$idioma['Licencias']="Licencias";
$idioma['NoRespondeTelf']="No Responde Telf";
$idioma['NotificacionPadres']="Notificación Padres";
$idioma['Felicitaciones']="Felicitaciones";
$idioma['RevisarConstantemente']="Se les insinua revisar constantemente las observaciones por Internet";
?>