<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="NVerTareas";
$jsFile="tareas/mostrar.js";
$subtitulo1="Configuracion";
$subtitulo2="Reporte";
$archivoInicial="formulario.php";
include_once("../../listar/curso.php");
?>