<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="NVerDeudores";
$jsFile="cuotas/deudores.js";
$archivoInicial="formulario.php";
$subtitulo1="Configuracion";
$subtitulo2="Reporte";
$horizontal=2;
include_once("../../listar/curso.php");
?>