<?php
include_once("../../login/check.php");
$titulo="NBoletaDatosAlumno";
$subtitulo1="BoletaDatos";
$folder="../../";
$icono="icon-print";
$jsFile="alumno/boletadatos.js";
include_once("../../listar/listado.php");
?>