<?php
include_once("../../login/check.php");
$titulo="NAgendaDigital";
$icono="icon-signal";
$subtitulo1="EstadisticaGeneralAgenda";
$folder="../../";
$jsFile="agenda/total.js";
include_once("../../listar/listado.php");
?>
