<?php
include_once("../../login/check.php");
$titulo="NModificarNotasCualitativasDocentes";
$subtitulo1="Configuracion";
$folder="../../";
$jsFile="notas/vernotascualitativoadministrativo.js";
$archivoInicial="formulario.php";
include_once("../../listar/docente.php");
?>