<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="ExportarNotasCualitativasCsvBimestre";
$subtitulo1="Configuracion";
$subtitulo2="Reporte";
$horizontal=2;
$datoInicial=1;
$archivoInicial="formulario.php";
$jsFile="seguridad/exportarcsvgeneralcualitativo.js";
include_once("../../listar/curso.php");
?>