<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="NImpresionBoletin";
$subtitulo1="Boletin";
$icono="icon-file";
$jsFile="notas/boletines.js";
include_once("../../listar/listado.php");
?>