<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="EnvioMasivo";
$subtitulo1="Configuracion";
$subtitulo2="Resultado";
$jsFile="sms/enviomasivo.js";
$archivoInicial="formulario.php";
include_once("../../listar/curso.php");
?>