<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="NEstadisticasInscritos";
$jsFile="alumno/estadisticas.js";
$icono="icon-signal";
$subtitulo1="Estadísticas";
include_once("../../listar/listado.php");
?>