<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="PromedioCursos";
$icono1="icon-cog";
$subtitulo1="Configuracion";
$icono1="icon-file";
$subtitulo2="Reporte";
$datoInicial=1;
$horizontal=2;
$archivoInicial="formulario.php";
$jsFile="notas/promediocurso.js";
include_once("../../listar/curso.php");
?>