<?php
include_once("../../login/check.php");
$folder="../../";
$titulo="NReporteFaltaAtrasos";
$subtitulo1="Configuracion";
$subtitulo2="Reporte";
$jsFile="agenda/reporteasistencia.js";
$archivoInicial="formulario.php";
include_once("../../listar/curso.php");
?>