<?php
include_once("../../login/check.php");
$titulo="NRegistroFaltas";
$subtitulo1="Configuracion";
$subtitulo2="Detalle";
$folder="../../";
$jsFile="asistencia/registrofalta.js";
include_once("../../listar/curso.php");
?>