<?php
include_once("../../login/check.php");
$titulo="NTarjetaCuotas";
$subtitulo1="TarjetaCuotas";
$folder="../../";
$icono="icon-print";
$jsFile="alumno/tarjetacuotas.js";
include_once("../../listar/listado.php");
?>