<?php
include_once("../../login/check.php");
$titulo="NAlumnoPorCurso";
$subtitulo1="Configuracion";
$subtitulo2="Reporte";
$folder="../../";
$jsFile="reporte/reportecurso.js";
include_once("../../listar/curso.php");
?>